--------------------------------------------------------
--  DDL for Table CONDITION_ACTIONS
--------------------------------------------------------

  CREATE TABLE "CONDITION_ACTIONS" 
   (	"ACTION_ID" NUMBER, 
	"CONDITION_ID" NUMBER, 
	"ACTION_TYPE" VARCHAR2(50 BYTE), 
	"TARGET_TYPE" VARCHAR2(20 BYTE), 
	"TARGET_ID" NUMBER, 
	"ACTION_VALUE" VARCHAR2(1000 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Table ELEMENT_CHOICES
--------------------------------------------------------

  CREATE TABLE "ELEMENT_CHOICES" 
   (	"CHOICE_ID" NUMBER, 
	"ELEMENT_ID" NUMBER, 
	"CHOICE_VALUE" VARCHAR2(255 BYTE), 
	"CHOICE_TEXT" VARCHAR2(255 BYTE), 
	"CHOICE_ORDER" NUMBER, 
	"IS_SELECTED" NUMBER(1,0) DEFAULT 0, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Table ELEMENT_TYPES
--------------------------------------------------------

  CREATE TABLE "ELEMENT_TYPES" 
   (	"TYPE_ID" NUMBER, 
	"TYPE_NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"HAS_CHOICES" NUMBER(1,0) DEFAULT 0, 
	"HAS_MULTIPLE_VALUES" NUMBER(1,0) DEFAULT 0, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Table ELEMENT_VALIDATORS
--------------------------------------------------------

  CREATE TABLE "ELEMENT_VALIDATORS" 
   (	"VALIDATOR_ID" NUMBER, 
	"ELEMENT_ID" NUMBER, 
	"VALIDATOR_TYPE" VARCHAR2(50 BYTE), 
	"ERROR_TEXT" VARCHAR2(500 BYTE), 
	"MIN_VALUE" VARCHAR2(100 BYTE), 
	"MAX_VALUE" VARCHAR2(100 BYTE), 
	"REGEX" VARCHAR2(500 BYTE), 
	"EXPRESSION" VARCHAR2(1000 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Table FORM_CALCULATED_VALUES
--------------------------------------------------------

  CREATE TABLE "FORM_CALCULATED_VALUES" 
   (	"CALC_ID" NUMBER, 
	"FORM_ID" NUMBER, 
	"CALC_NAME" VARCHAR2(100 BYTE), 
	"EXPRESSION" VARCHAR2(1000 BYTE), 
	"INCLUDE_IN_RESULT" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Table FORM_CONDITIONS
--------------------------------------------------------

  CREATE TABLE "FORM_CONDITIONS" 
   (	"CONDITION_ID" NUMBER, 
	"FORM_ID" NUMBER, 
	"CONDITION_NAME" VARCHAR2(100 BYTE), 
	"EXPRESSION" VARCHAR2(1000 BYTE), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Table FORM_ELEMENTS
--------------------------------------------------------

  CREATE TABLE "FORM_ELEMENTS" 
   (	"ELEMENT_ID" NUMBER, 
	"PAGE_ID" NUMBER, 
	"ELEMENT_TYPE" VARCHAR2(50 BYTE), 
	"ELEMENT_NAME" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"TITLE_LOCATION" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"DESCRIPTION_LOCATION" VARCHAR2(50 BYTE), 
	"IS_REQUIRED" NUMBER(1,0) DEFAULT 0, 
	"VISIBLE_IF" VARCHAR2(1000 BYTE), 
	"DEFAULT_VALUE" VARCHAR2(1000 BYTE), 
	"DEFAULT_VALUE_EXPRESSION" VARCHAR2(1000 BYTE), 
	"WIDTH" VARCHAR2(50 BYTE), 
	"MIN_WIDTH" VARCHAR2(50 BYTE), 
	"PLACEHOLDER" VARCHAR2(255 BYTE), 
	"INPUT_TYPE" VARCHAR2(50 BYTE), 
	"ALLOW_CLEAR" NUMBER(1,0) DEFAULT 1, 
	"START_WITH_NEW_LINE" NUMBER(1,0) DEFAULT 1, 
	"ELEMENT_ORDER" NUMBER, 
	"AUTO_GROW" NUMBER(1,0) DEFAULT 0, 
	"ALLOW_RESIZE" NUMBER(1,0) DEFAULT 1, 
	"HTML_CONTENT" CLOB, 
	"IMAGE_LINK" VARCHAR2(500 BYTE), 
	"IMAGE_FIT" VARCHAR2(50 BYTE), 
	"IMAGE_HEIGHT" VARCHAR2(50 BYTE), 
	"IMAGE_WIDTH" VARCHAR2(50 BYTE), 
	"USE_DISPLAY_VALUES" NUMBER(1,0) DEFAULT 0, 
	"PARENT_ELEMENT_ID" NUMBER, 
	"MAX_RATE" NUMBER, 
	"MIN_RATE" NUMBER DEFAULT 1, 
	"STEP" NUMBER DEFAULT 1, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" 
 LOB ("HTML_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FORM_PAGES
--------------------------------------------------------

  CREATE TABLE "FORM_PAGES" 
   (	"PAGE_ID" NUMBER, 
	"FORM_ID" NUMBER, 
	"PAGE_NAME" VARCHAR2(100 BYTE), 
	"PAGE_TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" CLOB, 
	"PAGE_ORDER" NUMBER, 
	"NAVIGATION_TITLE" VARCHAR2(100 BYTE), 
	"NAVIGATION_DESCRIPTION" VARCHAR2(255 BYTE), 
	"VISIBLE_IF" VARCHAR2(1000 BYTE), 
	"IS_DYNAMIC_PANEL" NUMBER(1,0) DEFAULT 0, 
	"MIN_PANEL_COUNT" NUMBER DEFAULT 1, 
	"MAX_PANEL_COUNT" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FORMS
--------------------------------------------------------

  CREATE TABLE "FORMS" 
   (	"FORM_ID" NUMBER, 
	"PARENT_FORM_ID" NUMBER, 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" CLOB, 
	"LOGO_URL" VARCHAR2(500 BYTE), 
	"LOGO_WIDTH" VARCHAR2(50 BYTE), 
	"LOGO_HEIGHT" VARCHAR2(50 BYTE), 
	"COMPLETED_HTML" CLOB, 
	"STATUS" NUMBER DEFAULT 1, 
	"IS_TEMPLATE" NUMBER(1,0) DEFAULT 0, 
	"WIDTH_MODE" VARCHAR2(20 BYTE) DEFAULT 'static', 
	"WIDTH" VARCHAR2(20 BYTE), 
	"FIT_TO_CONTAINER" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE, 
	"PUBLISHED_AT" DATE, 
	"VERSION" NUMBER, 
	"OBJ_NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("COMPLETED_HTML") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SUBMISSION_CHOICE_VALUES
--------------------------------------------------------

  CREATE TABLE "SUBMISSION_CHOICE_VALUES" 
   (	"CHOICE_VALUE_ID" NUMBER, 
	"SUBMISSION_ID" NUMBER, 
	"ELEMENT_ID" NUMBER, 
	"ENTRY_ID" NUMBER, 
	"CHOICE_ID" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Table SUBMISSION_COMMENTS
--------------------------------------------------------

  CREATE TABLE "SUBMISSION_COMMENTS" 
   (	"COMMENT_ID" NUMBER, 
	"SUBMISSION_ID" NUMBER, 
	"COMMENT_TEXT" CLOB, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE, 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"UPDATED_BY" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TOOLS" 
 LOB ("COMMENT_TEXT") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table SUBMISSION_FILES
--------------------------------------------------------

  CREATE TABLE "SUBMISSION_FILES" 
   (	"FILE_ID" NUMBER, 
	"SUBMISSION_ID" NUMBER, 
	"ELEMENT_ID" NUMBER, 
	"ENTRY_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"FILE_SIZE" NUMBER, 
	"FILE_LOB" BLOB, 
	"CONTENT_TYPE" VARCHAR2(100 BYTE), 
	"STORAGE_PATH" VARCHAR2(1000 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" 
 LOB ("FILE_LOB") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SUBMISSION_HISTORY
--------------------------------------------------------

  CREATE TABLE "SUBMISSION_HISTORY" 
   (	"HISTORY_ID" NUMBER, 
	"SUBMISSION_ID" NUMBER, 
	"ELEMENT_ID" NUMBER, 
	"STAGE_ID" NUMBER, 
	"ACTION_TYPE" VARCHAR2(50 BYTE), 
	"OLD_VALUE" CLOB, 
	"NEW_VALUE" CLOB, 
	"CHANGED_BY" VARCHAR2(30 BYTE), 
	"CHANGED_AT" DATE DEFAULT SYSDATE, 
	"VALUE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TOOLS" 
 LOB ("OLD_VALUE") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("NEW_VALUE") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table SUBMISSION_PANEL_ENTRIES
--------------------------------------------------------

  CREATE TABLE "SUBMISSION_PANEL_ENTRIES" 
   (	"ENTRY_ID" NUMBER, 
	"SUBMISSION_ID" NUMBER, 
	"PAGE_ID" NUMBER, 
	"ENTRY_INDEX" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Table SUBMISSION_VALUES
--------------------------------------------------------

  CREATE TABLE "SUBMISSION_VALUES" 
   (	"VALUE_ID" NUMBER, 
	"SUBMISSION_ID" NUMBER, 
	"ELEMENT_ID" NUMBER, 
	"ENTRY_ID" NUMBER, 
	"DATE_VALUE" DATE, 
	"CLOB_VALUE" CLOB, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" 
 LOB ("CLOB_VALUE") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SUBMISSIONS_FORM
--------------------------------------------------------

  CREATE TABLE "SUBMISSIONS_FORM" 
   (	"SUBMISSION_ID" NUMBER, 
	"FORM_ID" NUMBER, 
	"WORKFLOW_ID" NUMBER, 
	"CURRENT_STAGE_ID" NUMBER, 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" CLOB, 
	"SUBMITTED_BY" VARCHAR2(30 BYTE), 
	"ASSIGNED_TO" VARCHAR2(30 BYTE), 
	"STATUS" NUMBER, 
	"SUBMITTED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE, 
	"IP_ADDRESS" VARCHAR2(45 BYTE), 
	"USER_AGENT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table WORKFLOW_AUTOMATIONS
--------------------------------------------------------

  CREATE TABLE "WORKFLOW_AUTOMATIONS" 
   (	"AUTOMATION_ID" NUMBER, 
	"WORKFLOW_ID" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"TRIGGER_TYPE" VARCHAR2(50 BYTE), 
	"TRIGGER_CONDITION" VARCHAR2(1000 BYTE), 
	"ACTION_TYPE" VARCHAR2(50 BYTE), 
	"ACTION_CONFIG" CLOB, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TOOLS" 
 LOB ("ACTION_CONFIG") STORE AS SECUREFILE (
  TABLESPACE "TOOLS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table WORKFLOW_STAGES
--------------------------------------------------------

  CREATE TABLE "WORKFLOW_STAGES" 
   (	"STAGE_ID" NUMBER, 
	"WORKFLOW_ID" NUMBER, 
	"STAGE_NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"COLOR" VARCHAR2(20 BYTE), 
	"STAGE_ORDER" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Table WORKFLOWS
--------------------------------------------------------

  CREATE TABLE "WORKFLOWS" 
   (	"WORKFLOW_ID" NUMBER, 
	"FORM_ID" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237742
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237742" ON "CONDITION_ACTIONS" ("ACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237715
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237715" ON "ELEMENT_CHOICES" ("CHOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index UK_CHOICE_ELEMENT_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_CHOICE_ELEMENT_ORDER" ON "ELEMENT_CHOICES" ("ELEMENT_ID", "CHOICE_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237828
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237828" ON "ELEMENT_TYPES" ("TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237829
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237829" ON "ELEMENT_TYPES" ("TYPE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237721
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237721" ON "ELEMENT_VALIDATORS" ("VALIDATOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237727
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237727" ON "FORM_CALCULATED_VALUES" ("CALC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237735
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237735" ON "FORM_CONDITIONS" ("CONDITION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237706
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237706" ON "FORM_ELEMENTS" ("ELEMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index UK_ELEMENT_PAGE_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_ELEMENT_PAGE_ORDER" ON "FORM_ELEMENTS" ("PAGE_ID", "ELEMENT_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237697
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237697" ON "FORM_PAGES" ("PAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index UK_PAGE_FORM_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_PAGE_FORM_ORDER" ON "FORM_PAGES" ("FORM_ID", "PAGE_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237933
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237933" ON "FORMS" ("FORM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237793
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237793" ON "SUBMISSION_CHOICE_VALUES" ("CHOICE_VALUE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index UK_SUBMISSION_CHOICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_SUBMISSION_CHOICE" ON "SUBMISSION_CHOICE_VALUES" ("SUBMISSION_ID", "ELEMENT_ID", "ENTRY_ID", "CHOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237813
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237813" ON "SUBMISSION_COMMENTS" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00238008
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00238008" ON "SUBMISSION_FILES" ("FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237818
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237818" ON "SUBMISSION_HISTORY" ("HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237778
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237778" ON "SUBMISSION_PANEL_ENTRIES" ("ENTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237785
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237785" ON "SUBMISSION_VALUES" ("VALUE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237900
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237900" ON "SUBMISSIONS_FORM" ("SUBMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237765
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237765" ON "WORKFLOW_AUTOMATIONS" ("AUTOMATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237755
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237755" ON "WORKFLOW_STAGES" ("STAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index UK_STAGE_WORKFLOW_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_STAGE_WORKFLOW_ORDER" ON "WORKFLOW_STAGES" ("WORKFLOW_ID", "STAGE_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00237749
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00237749" ON "WORKFLOWS" ("WORKFLOW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS" ;
--------------------------------------------------------
--  Constraints for Table CONDITION_ACTIONS
--------------------------------------------------------

  ALTER TABLE "CONDITION_ACTIONS" MODIFY ("CONDITION_ID" NOT NULL ENABLE);
  ALTER TABLE "CONDITION_ACTIONS" MODIFY ("ACTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CONDITION_ACTIONS" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CONDITION_ACTIONS" MODIFY ("TARGET_ID" NOT NULL ENABLE);
  ALTER TABLE "CONDITION_ACTIONS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CONDITION_ACTIONS" ADD PRIMARY KEY ("ACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELEMENT_CHOICES
--------------------------------------------------------

  ALTER TABLE "ELEMENT_CHOICES" ADD CONSTRAINT "CHK_CHOICE_SELECTED" CHECK (is_selected IN (0, 1)) ENABLE;
  ALTER TABLE "ELEMENT_CHOICES" MODIFY ("ELEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_CHOICES" MODIFY ("CHOICE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_CHOICES" MODIFY ("CHOICE_ORDER" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_CHOICES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_CHOICES" ADD PRIMARY KEY ("CHOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
  ALTER TABLE "ELEMENT_CHOICES" ADD CONSTRAINT "UK_CHOICE_ELEMENT_ORDER" UNIQUE ("ELEMENT_ID", "CHOICE_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELEMENT_TYPES
--------------------------------------------------------

  ALTER TABLE "ELEMENT_TYPES" ADD CONSTRAINT "CHK_ETYPE_HAS_CHOICES" CHECK (has_choices IN (0, 1)) ENABLE;
  ALTER TABLE "ELEMENT_TYPES" ADD CONSTRAINT "CHK_ETYPE_MULTIPLE_VALS" CHECK (has_multiple_values IN (0, 1)) ENABLE;
  ALTER TABLE "ELEMENT_TYPES" MODIFY ("TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_TYPES" MODIFY ("HAS_CHOICES" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_TYPES" MODIFY ("HAS_MULTIPLE_VALUES" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_TYPES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_TYPES" ADD PRIMARY KEY ("TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
  ALTER TABLE "ELEMENT_TYPES" ADD UNIQUE ("TYPE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELEMENT_VALIDATORS
--------------------------------------------------------

  ALTER TABLE "ELEMENT_VALIDATORS" MODIFY ("ELEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_VALIDATORS" MODIFY ("VALIDATOR_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_VALIDATORS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "ELEMENT_VALIDATORS" ADD PRIMARY KEY ("VALIDATOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORM_CALCULATED_VALUES
--------------------------------------------------------

  ALTER TABLE "FORM_CALCULATED_VALUES" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "FORM_CALCULATED_VALUES" MODIFY ("CALC_NAME" NOT NULL ENABLE);
  ALTER TABLE "FORM_CALCULATED_VALUES" MODIFY ("EXPRESSION" NOT NULL ENABLE);
  ALTER TABLE "FORM_CALCULATED_VALUES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FORM_CALCULATED_VALUES" ADD PRIMARY KEY ("CALC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORM_CONDITIONS
--------------------------------------------------------

  ALTER TABLE "FORM_CONDITIONS" ADD CONSTRAINT "CHK_CONDITION_ACTIVE" CHECK (is_active IN (0, 1)) ENABLE;
  ALTER TABLE "FORM_CONDITIONS" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "FORM_CONDITIONS" MODIFY ("CONDITION_NAME" NOT NULL ENABLE);
  ALTER TABLE "FORM_CONDITIONS" MODIFY ("EXPRESSION" NOT NULL ENABLE);
  ALTER TABLE "FORM_CONDITIONS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "FORM_CONDITIONS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FORM_CONDITIONS" ADD PRIMARY KEY ("CONDITION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORM_ELEMENTS
--------------------------------------------------------

  ALTER TABLE "FORM_ELEMENTS" MODIFY ("PAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "FORM_ELEMENTS" MODIFY ("ELEMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FORM_ELEMENTS" MODIFY ("ELEMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "FORM_ELEMENTS" MODIFY ("IS_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "FORM_ELEMENTS" MODIFY ("ELEMENT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "FORM_ELEMENTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FORM_ELEMENTS" ADD PRIMARY KEY ("ELEMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
  ALTER TABLE "FORM_ELEMENTS" ADD CONSTRAINT "UK_ELEMENT_PAGE_ORDER" UNIQUE ("PAGE_ID", "ELEMENT_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORM_PAGES
--------------------------------------------------------

  ALTER TABLE "FORM_PAGES" ADD CONSTRAINT "CHK_PAGE_DYNAMIC" CHECK (is_dynamic_panel IN (0, 1)) ENABLE;
  ALTER TABLE "FORM_PAGES" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "FORM_PAGES" MODIFY ("PAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "FORM_PAGES" MODIFY ("PAGE_ORDER" NOT NULL ENABLE);
  ALTER TABLE "FORM_PAGES" MODIFY ("IS_DYNAMIC_PANEL" NOT NULL ENABLE);
  ALTER TABLE "FORM_PAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FORM_PAGES" ADD PRIMARY KEY ("PAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
  ALTER TABLE "FORM_PAGES" ADD CONSTRAINT "UK_PAGE_FORM_ORDER" UNIQUE ("FORM_ID", "PAGE_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORMS
--------------------------------------------------------

  ALTER TABLE "FORMS" ADD CONSTRAINT "CHK_FORM_TEMPLATE" CHECK (is_template IN (0, 1)) ENABLE;
  ALTER TABLE "FORMS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "FORMS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "FORMS" MODIFY ("IS_TEMPLATE" NOT NULL ENABLE);
  ALTER TABLE "FORMS" MODIFY ("FIT_TO_CONTAINER" NOT NULL ENABLE);
  ALTER TABLE "FORMS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FORMS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FORMS" ADD PRIMARY KEY ("FORM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBMISSION_CHOICE_VALUES
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_CHOICE_VALUES" MODIFY ("SUBMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_CHOICE_VALUES" MODIFY ("ELEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_CHOICE_VALUES" MODIFY ("CHOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_CHOICE_VALUES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_CHOICE_VALUES" ADD PRIMARY KEY ("CHOICE_VALUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
  ALTER TABLE "SUBMISSION_CHOICE_VALUES" ADD CONSTRAINT "UK_SUBMISSION_CHOICE" UNIQUE ("SUBMISSION_ID", "ELEMENT_ID", "ENTRY_ID", "CHOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBMISSION_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_COMMENTS" MODIFY ("SUBMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_COMMENTS" MODIFY ("COMMENT_TEXT" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_COMMENTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_COMMENTS" ADD PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBMISSION_FILES
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_FILES" MODIFY ("SUBMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_FILES" MODIFY ("ELEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_FILES" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_FILES" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_FILES" MODIFY ("CONTENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_FILES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_FILES" ADD PRIMARY KEY ("FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBMISSION_HISTORY
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_HISTORY" MODIFY ("SUBMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_HISTORY" MODIFY ("ACTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_HISTORY" MODIFY ("CHANGED_AT" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_HISTORY" ADD PRIMARY KEY ("HISTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBMISSION_PANEL_ENTRIES
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_PANEL_ENTRIES" MODIFY ("SUBMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_PANEL_ENTRIES" MODIFY ("PAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_PANEL_ENTRIES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_PANEL_ENTRIES" ADD PRIMARY KEY ("ENTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBMISSION_VALUES
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_VALUES" MODIFY ("SUBMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_VALUES" MODIFY ("ELEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_VALUES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSION_VALUES" ADD PRIMARY KEY ("VALUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBMISSIONS_FORM
--------------------------------------------------------

  ALTER TABLE "SUBMISSIONS_FORM" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSIONS_FORM" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSIONS_FORM" MODIFY ("SUBMITTED_AT" NOT NULL ENABLE);
  ALTER TABLE "SUBMISSIONS_FORM" ADD PRIMARY KEY ("SUBMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKFLOW_AUTOMATIONS
--------------------------------------------------------

  ALTER TABLE "WORKFLOW_AUTOMATIONS" MODIFY ("WORKFLOW_ID" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_AUTOMATIONS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_AUTOMATIONS" MODIFY ("TRIGGER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_AUTOMATIONS" MODIFY ("ACTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_AUTOMATIONS" MODIFY ("ACTION_CONFIG" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_AUTOMATIONS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_AUTOMATIONS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_AUTOMATIONS" ADD PRIMARY KEY ("AUTOMATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKFLOW_STAGES
--------------------------------------------------------

  ALTER TABLE "WORKFLOW_STAGES" MODIFY ("WORKFLOW_ID" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_STAGES" MODIFY ("STAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_STAGES" MODIFY ("STAGE_ORDER" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_STAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOW_STAGES" ADD PRIMARY KEY ("STAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS"  ENABLE;
  ALTER TABLE "WORKFLOW_STAGES" ADD CONSTRAINT "UK_STAGE_WORKFLOW_ORDER" UNIQUE ("WORKFLOW_ID", "STAGE_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKFLOWS
--------------------------------------------------------

  ALTER TABLE "WORKFLOWS" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOWS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOWS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOWS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOWS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "WORKFLOWS" ADD PRIMARY KEY ("WORKFLOW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TOOLS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONDITION_ACTIONS
--------------------------------------------------------

  ALTER TABLE "CONDITION_ACTIONS" ADD CONSTRAINT "FK_ACTIONS_CONDITION" FOREIGN KEY ("CONDITION_ID")
	  REFERENCES "FORM_CONDITIONS" ("CONDITION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ELEMENT_CHOICES
--------------------------------------------------------

  ALTER TABLE "ELEMENT_CHOICES" ADD CONSTRAINT "FK_CHOICES_ELEMENT" FOREIGN KEY ("ELEMENT_ID")
	  REFERENCES "FORM_ELEMENTS" ("ELEMENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ELEMENT_VALIDATORS
--------------------------------------------------------

  ALTER TABLE "ELEMENT_VALIDATORS" ADD CONSTRAINT "FK_VALIDATORS_ELEMENT" FOREIGN KEY ("ELEMENT_ID")
	  REFERENCES "FORM_ELEMENTS" ("ELEMENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORM_ELEMENTS
--------------------------------------------------------

  ALTER TABLE "FORM_ELEMENTS" ADD CONSTRAINT "FK_ELEMENTS_PAGE" FOREIGN KEY ("PAGE_ID")
	  REFERENCES "FORM_PAGES" ("PAGE_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FORM_ELEMENTS" ADD CONSTRAINT "FK_ELEMENTS_PARENT" FOREIGN KEY ("PARENT_ELEMENT_ID")
	  REFERENCES "FORM_ELEMENTS" ("ELEMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORMS
--------------------------------------------------------

  ALTER TABLE "FORMS" ADD CONSTRAINT "FK_FORM_PARENT" FOREIGN KEY ("PARENT_FORM_ID")
	  REFERENCES "FORMS" ("FORM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBMISSION_CHOICE_VALUES
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_CHOICE_VALUES" ADD CONSTRAINT "FK_SUB_CHOICES_CHOICE" FOREIGN KEY ("CHOICE_ID")
	  REFERENCES "ELEMENT_CHOICES" ("CHOICE_ID") ENABLE;
  ALTER TABLE "SUBMISSION_CHOICE_VALUES" ADD CONSTRAINT "FK_SUB_CHOICES_ELEMENT" FOREIGN KEY ("ELEMENT_ID")
	  REFERENCES "FORM_ELEMENTS" ("ELEMENT_ID") ENABLE;
  ALTER TABLE "SUBMISSION_CHOICE_VALUES" ADD CONSTRAINT "FK_SUB_CHOICES_ENTRY" FOREIGN KEY ("ENTRY_ID")
	  REFERENCES "SUBMISSION_PANEL_ENTRIES" ("ENTRY_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBMISSION_FILES
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_FILES" ADD CONSTRAINT "FK_SUB_FILES_ELEMENT" FOREIGN KEY ("ELEMENT_ID")
	  REFERENCES "FORM_ELEMENTS" ("ELEMENT_ID") ENABLE;
  ALTER TABLE "SUBMISSION_FILES" ADD CONSTRAINT "FK_SUB_FILES_ENTRY" FOREIGN KEY ("ENTRY_ID")
	  REFERENCES "SUBMISSION_PANEL_ENTRIES" ("ENTRY_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SUBMISSION_FILES" ADD CONSTRAINT "FK_SUB_FILES_SUBMISSION" FOREIGN KEY ("SUBMISSION_ID")
	  REFERENCES "SUBMISSIONS_FORM" ("SUBMISSION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBMISSION_HISTORY
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_HISTORY" ADD CONSTRAINT "FK_HISTORY_ELEMENT" FOREIGN KEY ("ELEMENT_ID")
	  REFERENCES "FORM_ELEMENTS" ("ELEMENT_ID") ENABLE;
  ALTER TABLE "SUBMISSION_HISTORY" ADD CONSTRAINT "FK_HISTORY_STAGE" FOREIGN KEY ("STAGE_ID")
	  REFERENCES "WORKFLOW_STAGES" ("STAGE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBMISSION_PANEL_ENTRIES
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_PANEL_ENTRIES" ADD CONSTRAINT "FK_PANEL_ENTRIES_PAGE" FOREIGN KEY ("PAGE_ID")
	  REFERENCES "FORM_PAGES" ("PAGE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBMISSION_VALUES
--------------------------------------------------------

  ALTER TABLE "SUBMISSION_VALUES" ADD CONSTRAINT "FK_SUB_VALUES_ELEMENT" FOREIGN KEY ("ELEMENT_ID")
	  REFERENCES "FORM_ELEMENTS" ("ELEMENT_ID") ENABLE;
  ALTER TABLE "SUBMISSION_VALUES" ADD CONSTRAINT "FK_SUB_VALUES_ENTRY" FOREIGN KEY ("ENTRY_ID")
	  REFERENCES "SUBMISSION_PANEL_ENTRIES" ("ENTRY_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBMISSIONS_FORM
--------------------------------------------------------

  ALTER TABLE "SUBMISSIONS_FORM" ADD CONSTRAINT "FK_SUBMISSIONS_STAGE" FOREIGN KEY ("CURRENT_STAGE_ID")
	  REFERENCES "WORKFLOW_STAGES" ("STAGE_ID") ENABLE;
  ALTER TABLE "SUBMISSIONS_FORM" ADD CONSTRAINT "FK_SUBMISSIONS_WORKFLOW" FOREIGN KEY ("WORKFLOW_ID")
	  REFERENCES "WORKFLOWS" ("WORKFLOW_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORKFLOW_AUTOMATIONS
--------------------------------------------------------

  ALTER TABLE "WORKFLOW_AUTOMATIONS" ADD CONSTRAINT "FK_AUTOMATIONS_WORKFLOW" FOREIGN KEY ("WORKFLOW_ID")
	  REFERENCES "WORKFLOWS" ("WORKFLOW_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORKFLOW_STAGES
--------------------------------------------------------

  ALTER TABLE "WORKFLOW_STAGES" ADD CONSTRAINT "FK_STAGES_WORKFLOW" FOREIGN KEY ("WORKFLOW_ID")
	  REFERENCES "WORKFLOWS" ("WORKFLOW_ID") ON DELETE CASCADE ENABLE;
